# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-19 10:15
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='UserEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('public_key', models.UUIDField(verbose_name='publicKey')),
                ('private_key', models.UUIDField(db_index=True, verbose_name='privateKey')),
            ],
        ),
        migrations.AddField(
            model_name='datastore',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receiveform.UserEntity'),
        ),
    ]
