# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 17:39
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('receiveform', '0001_initial'), ('receiveform', '0002_auto_20160129_1738')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='UserEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_key', models.UUIDField(default='f1bfe7e7-b270-4d04-bb20-a7d07cdc4e91', verbose_name='publicKey')),
                ('private_key', models.UUIDField(default='57e87942-9623-41e7-8144-6a2ca74b5f84', verbose_name='privateKey')),
                ('email', models.EmailField(default=None, max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='datastore',
            name='userEntity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receiveform.UserEntity'),
        ),
    ]
